version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - PGUSER=${DB_USERNAME}
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d taskmanagerdb"]
      interval: 5s
      timeout: 5s
      retries: 5
  server:
    build: .
    ports:
      - 3000:3000
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env