services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=taskmanagerdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PGHOST=db